require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Max: 30
  IgnoredMethods:
    - describe

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
